name             'icinga2'
maintainer       'Karol Pasternak'
maintainer_email 'karol@pasternak.pro'
license          'All rights reserved'
description      'Installs/Configures icinga2'
long_description 'Installs/Configures icinga2'
version          '0.1.0'
depends          'yum'
depends          'mariadb'
